#!/bin/bash
#by lemys lopez lemyskaman@gmail.com

#the path to get the orchid base stubs for copiying
SOURCE_PATH="$(dirname $(readlink -f $0))/orchid_clean"
TARGET_PATH=$1

if [ -z "$TARGET_PATH" ] 
then
TARGET_PATH=.
fi

TARGET_PATH=$(readlink -f $TARGET_PATH)
echo ""
echo ""
echo "This script will DELETE all files inside:"
echo ""
echo "    ${bold}$TARGET_PATH${normal} "
echo ""
read -p "Are you sure to continue? [Yy]" -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Aborted!"
    exit 1
fi

shopt -s extglob


echo "Deleting current target path files "
rm -r -f -v !(".git"|".env"|".gitignore"|.|..)
echo "$TARGET_PATH files deleted "
echo ""
echo "Copiying a new boilerplate for klorchid"
cp -a $SOURCE_PATH/.  $TARGET_PATH/

shopt -u extglob

echo "composer update is needed and will be runned"
cd $TARGET_PATH
composer update 

cd -
echo "Done!"
