#! /bin/bash

PHP_VERSION=$1

if [ -z "$PHP_VERSION" ] 
then
echo "please pass as param the wanted php version number"
exit 1
fi


read -p "Are you sure? [Y/n] " -n 1 -r


echo ""
if [[ $REPLY =~ ^[Yy]$ ]]
then


echo  "installing php version:"
echo $PHP_VERSION



sudo bash  install_php_and_commons_ubuntu_18.04

cd ~


echo "installing mariadb (mysql)"
echo "adding maria db official repo for debian 10"
sudo apt-get install software-properties-common dirmngr apt-transport-https
sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
sudo add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.5/debian buster main'


sudo apt update 

sudo apt install mariadb-server nginx build-essential git-all sqlite3 nodejs npm -y

sudo apt install php$PHP_VERSION-{fpm,sqlite3,mysql,xml,xmlrpc,curl,gd,imagick,cli,dev,imap,mbstring,opcache,soap,zip,intl,bcmath,bz2,xdebug,ctype,gmp,bcmath,dev} php$PHP_VERSION -y

fi