#! /bin/bash

PHP_VERSION=$1
echo  "installing php version:"
echo $PHP_VERSION


read -p "Are you sure? [Y/n] " -n 1 -r


echo ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
sudo apt install php$PHP_VERSION php$
PHP_VERSION-{fpm,mysql,xml,xmlrpc,curl,gd,imagick,cli,dev,imap,mbstring,opcache,soap,zip,intl,bcmath} -y
fi

