#! /bin/bash

PHP_VERSION=$1

if [ -z "$PHP_VERSION" ] 
then
echo "please pass as param the wanted php version number"
exit 1
fi

echo  "installing php version:"
echo $PHP_VERSION


read -p "Are you sure? [Y/n] " -n 1 -r


echo ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
sudo apt install  php$PHP_VERSION-{fpm,sqlite,mysql,xml,xmlrpc,curl,gd,imagick,cli,dev,imap,mbstring,opcache,soap,zip,intl,bcmath,bz2} php$PHP_VERSION -y
fi
