#!/bin/bash
#Author: Lemys Lopez @lemyskaman
#A bash script to automate the proces of virtual box machines snapshoting 


date_string=$(date +%d_%m_%y)
time_string=$(date +%H_%M_%S)
snapshot_name_prefix="bk_"
snapshot_name_tail=_$date_string-$time_string

vm_name=$1
extra_name_string=$2


if [[ $# -lt 1 ]]; then
        echo "Name of the virtual machine as first param is mandatory"
        echo "runnig example:"
        echo ""
        echo "$ take_snapshot <vm name> "
        exit 1
fi


vboxmanage snapshot $vm_name take $snapshot_name_prefix$extra_name_string$snapshot_name_tail --description="Saved snapshot taken by a script $0 at $(date)"

